### ISSUE TITLE
Media Select is not working after installing 

### ISSUE THREAD

**Issue by BartoTato** [skttl/our-umbraco-matryoshka#11] opened 2020-03-17 21:48 UTC
Hi

We have a fairly large site and after installing this package select media button is not working. Uninstalling package does not help.

Can anyone help?

**Comment by AussieInSeattle** [comment] 2020-03-18 06:16
I had the same issue on Umbraco Cloud version 8.5.4 - I ran into the issue when trying to select media via an RTE - uninstalling worked for me after spending most of the day trying to work out a solution via debugging core angular code :-(

Maybe change the version id in config/clientdependency.config to ensure the uninstall worked?

**Comment by skttl** [comment] 2020-03-18 07:18
Let me know if the changed version id works.

**Comment by BartoTato** [comment] 2020-03-18 07:21
Hi 
Thank you for a quick reply. Uninstalling worked this time. I didn't have to change version id. (Lots of stress) ...I would love to use your plugin again as our clients are used to tabs. But media upload has to work. 

Thanks.

**Comment by skttl** [comment] 2020-03-18 07:22
Duplicate of #7

**Closed by skttl** 2020-03-18 07:22 UTC
