### ISSUE TITLE
Issue when inserting media images into Rich Text Editor

### ISSUE THREAD

**Issue by prgriffithsdev** [skttl/our-umbraco-matryoshka#14] opened 2020-04-12 09:22 UTC
Hi, 

Whilst using Umbraco version 8.5.4 (and 8.6) when attempting to insert an image (from the media section) into the Rich text area the select button doesn't update to allow me to submit the image.

I raised this issue on our forum https://our.umbraco.com/forum/using-umbraco-and-getting-started/101782-inserting-media-images-into-rich-text-editor-v8 but after some investigation i believe it could be related to the Our.Umbraco.Matryoshka package. When i remove the package it works as expected. 

Is it possible you could take a look please :) Really love the package and would like to keep it installed.

Many thanks

**Comment by skttl** [comment] 2020-04-12 09:37
Duplicate of #7

**Closed by skttl** 2020-04-12 09:37 UTC

**Comment by prgriffithsdev** [comment] 2020-04-12 09:47
Hi @skttl, 

That work around didn't work for me. Is there anything else i could try please?

Thanks
